### ISSUE TITLE
panic: XML syntax error on line 30: unescaped < inside quoted string [recovered]

### ISSUE THREAD

**Issue by zhuxiujia** [beevik/etree#63] opened 2018-12-20 13:48 UTC
this is my code:
```
<if test="page < 0" >limit #{page}, #{size}</if>
```
xml  can not  load   '<' , in element Property, it should be parsed
will panic: XML syntax error on line 30: unescaped < inside quoted string [recovered]

**Comment by beevik** [comment] 2019-01-09 02:06
This is caused by the go standard xml library's failure to parse an XML attribute string containing `<`.  According to the [XML specification](https://www.w3.org/TR/xml/), it is invalid for an attribute value to contain `<`.

**Comment by beevik** [comment] 2019-01-09 02:06
I am closing this issue, because the etree library is behaving as expected.

**Closed by beevik** 2019-01-09 02:06 UTC
